
name: build pull request
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1
      - name: setup jdk 17
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: |
          ./gradlew build spotbugs

      - name: set up reviewdog
        uses: reviewdog/action-setup@v1
      - name: upload spotbugs sarif report
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ./build/reports/spotbugs/main/spotbugs.sarif | reviewdog -name="spotbugs" -f=sarif -reporter=github-check -level=warning

  client_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1
      - name: setup jdk 17
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: run testmod
        uses: modmuss50/xvfb-action@v1
        with:
          run: ./gradlew runTestClient --stacktrace --warning-mode=fail
      #- uses: actions/upload-artifact@v4.3.1
      #  with:
      #    name: Test Screenshots
      #    path: run/screenshots

  server_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1
      - name: setup jdk 17
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: run testmod
        run: ./gradlew runTestServer --stacktrace --warning-mode=fail